### ISSUE TITLE
Can't resolve 'fs'

### ISSUE THREAD

**Issue by aihpoSSophia** [duartealexf/sql-ddl-to-json-schema#47] opened 2020-02-18 03:01 UTC
ERROR in ./node_modules/sql-ddl-to-json-schema/lib/parser.js
Module not found: Error: Can't resolve 'fs' in 'XXXX\node_modules\sql-ddl-to-json-schema\lib'

How to solve this problem?

**Comment by duartealexf** [comment] 2020-02-18 13:16
Hi @aihpoSSophia please provide the following information:

- Your operating system
- NodeJS version
- Steps you followed to get this error

Thanks! :)

**Comment by litice-wen** [comment] 2020-03-02 12:59
I have the same problem...
Browser environment：Chrome v80
Can you provide a browser version of the framework？

**Comment by litice-wen** [comment] 2020-03-02 13:07
I have the same problem...I'm running it in the browser.Browser does not support fs module.
Browser environment：Chrome v80
OS：MacOS 10.15.3
NodeJS：12.14.1
Can you provide a browser version of the framework？

**Comment by cristianpedroso** [comment] 2020-03-02 13:12
Thanks for providing this info.
I will have a look into it asap.

**Comment by duartealexf** [comment] 2020-03-02 13:13
Thank you for providing this info.
I will have a look at it asap.

**Comment by aihpoSSophia** [comment] 2020-03-03 02:46
Sorry to be late @duartealexf 

- OS: Windows 10
- NodeJS: 10.3.0
- Steps:  1. npm install sql-ddl-to-json-schema
              2. In component.ts:
	          const Parser = require('sql-ddl-to-json-schema');
	          const parser = new Parser('mysql');
              3. npm run copy&ng serve --proxy-config proxy.conf.json --port 4201 --base-href=/drds/

**Comment by duartealexf** [comment] 2020-03-03 12:53
@aihpoSSophia tks for the info. I take it it is also browser-based because of the Angular CLI you're using. I haven't looked at it yet, but I will take care of it this week.

**Comment by duartealexf** [comment] 2020-03-09 12:33
@aihpoSSophia @litice-wen I'm still working on it. I was able to reproduce the bug on Angular. It's going to take some time because I'm refactoring everything to Typescript, but I want to finish this ASAP.

A preview on the next update (3.2.x):
- Angular compatibility bugfixes;
- Typing definitions;

**Comment by duartealexf** [comment] 2020-03-11 13:46
Thank you again for the PR @aihpoSSophia.

It is merged and available in v3.1.3.

**Comment by duartealexf** [comment] 2020-03-22 06:22
@aihpoSSophia @litice-wen 

Version 4.0.0 is available with the fixes. It also includes typings definitions.
Please read [the changelog](https://github.com/duartealexf/sql-ddl-to-json-schema/blob/v4.0.0/CHANGELOG.md#400-2020-03-22) about a couple of breaking changes.

Cheers!

**Closed by duartealexf** 2020-03-22 06:22 UTC
Labels: bug, wip

**Comment by duartealexf** [comment] 2020-03-23 01:39
@aihpoSSophia @litice-wen

Version 4.0.0 had a bad built. Please use 4.0.1.

**Comment by litice-wen** [comment] 2020-03-23 01:44
Thank you very much.
